version: "2"
services:
  mirth-db:
    container_name: mirth-db_demo
    image: uwitech/postgresql
    volumes:
      - mirth-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mirthdb
      - POSTGRES_DB=mirthdb
      - POSTGRES_PASSWORD=mirthdb

  mirth:
    container_name: mirth-connect
    env_file: .env
    image: uwitech/mirth-connect
    depends_on:
      - mirth-db
    ports:
      - "8998:8998"
      - "8443:8443"

volumes:
  mirth-pgdata:
